### PR TITLE
Run tests through Circle CI

### PR DESCRIPTION
**Pull request by Etroid**
This PR does the following:
- Enables Circle CI integration 
- Runs tests for `feeds_migrate` on D 8.7.x
- Runs code sniffer and code coverage
- Added README.MD
- Added PR template

### CODE REVIEW

**Comment by Etroid** [comment]
@MegaChriz When you get a chance to take a look.

**Comment by MegaChriz** [comment]
composer.json
- I see you added some dev dependencies. I suppose these are all needed to be able to run tests through Cirlce CI?

README.md
- Nitpick: text should wrap at 80 chars.

phpunit.core.xml.dist
- I see you pointed the test suites to that of core, while they previously pointed to directories from feeds_migrate.
- In whitelist I see that feeds_migrate/test_modules is whitelisted, but that directory does not exist. I propose to add test modules directly in the tests directory, thus in feeds_migrate/tests/modules.

phpcs.xml
- I see you excluded css and js from the code standards check, but Drupal's code standards checker also support checking css code (and I think JS as well).

config.yml
Let's see if I can understand what it does:
1. You have three docker instances:
   - One with all the Drupal core files;
   - One with Selenium for browser tests;
   - One for the database. The database doesn't require a password?
2. working_directory specifies which tests to run?
3. restore_cache: sounds like that is used so composer dependencies only have to be downloaded once for the complete test suite run.
4. save_cache: specifies where to save the composer build?
5. update_dependencies:
     checkout: instructs to perform a composer install?
     The Drupal core directory is removed, is that because andrewberry/drupal_tests:0.4.0 comes with Drupal 8.6?
     I see that for some reason, the library "egulias/email-validator" is removed. Is that because Drupal 8.7 no longer ships with that library?
6. unit_kernel_tests: Unit tests and Kernel tests are ran as "one job". These test suites don't need Selenium, so I guess that's why they grouped together there.
7. functional_tests: functional tests and functional JS tests are also ran as "one job". Both of them depend on Selenium, so I guess that's why they grouped together.
8. code_sniffer: ode is checked for standards. All checks are performed, the checks don't stop on warnings/errors.
9. code_coverage: checks are performed to see how much code is covered by tests.
10. jobs: the actual jobs to run are specified, apparently listing the job details above gets ignored when the jobs are not explicitly defined as jobs.
  It mentions 'version: 2'. Is that the Circle CI version?
11. workflows: takes care that multiple tests can run at once.

PULL_REQUEST_TEMPLATE.md
This could probably be expanded further, but for now it is OK. We could use Webform's issue templates as inspiration.

**Comment by MegaChriz** [comment]
Looks good. I've updated the README.md. According to my editor, the text didn't wrap at 80 chars yet and I corrected that mostly.

**Comment by Etroid** [comment]
Sweet thanks, you can it approve it via the review process

**Review by MegaChriz — APPROVED** [review]

**Pull request merged**
